# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/news_settings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/settings/news_settings.proto',
  package='pogoprotos.settings',
  syntax='proto3',
  serialized_pb=_b('\n\'pogoprotos/settings/news_settings.proto\x12\x13pogoprotos.settings\"\x81\x01\n\x0cNewsSettings\x12\x34\n\x04news\x18\x01 \x03(\x0b\x32&.pogoprotos.settings.NewsSettings.News\x1a;\n\x04News\x12\x16\n\x0enews_bundle_id\x18\x01 \x01(\t\x12\x1b\n\x13\x65xclusive_countries\x18\x02 \x03(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_NEWSSETTINGS_NEWS = _descriptor.Descriptor(
  name='News',
  full_name='pogoprotos.settings.NewsSettings.News',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='news_bundle_id', full_name='pogoprotos.settings.NewsSettings.News.news_bundle_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exclusive_countries', full_name='pogoprotos.settings.NewsSettings.News.exclusive_countries', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=194,
)

_NEWSSETTINGS = _descriptor.Descriptor(
  name='NewsSettings',
  full_name='pogoprotos.settings.NewsSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='news', full_name='pogoprotos.settings.NewsSettings.news', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_NEWSSETTINGS_NEWS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=194,
)

_NEWSSETTINGS_NEWS.containing_type = _NEWSSETTINGS
_NEWSSETTINGS.fields_by_name['news'].message_type = _NEWSSETTINGS_NEWS
DESCRIPTOR.message_types_by_name['NewsSettings'] = _NEWSSETTINGS

NewsSettings = _reflection.GeneratedProtocolMessageType('NewsSettings', (_message.Message,), dict(

  News = _reflection.GeneratedProtocolMessageType('News', (_message.Message,), dict(
    DESCRIPTOR = _NEWSSETTINGS_NEWS,
    __module__ = 'pogoprotos.settings.news_settings_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.settings.NewsSettings.News)
    ))
  ,
  DESCRIPTOR = _NEWSSETTINGS,
  __module__ = 'pogoprotos.settings.news_settings_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.settings.NewsSettings)
  ))
_sym_db.RegisterMessage(NewsSettings)
_sym_db.RegisterMessage(NewsSettings.News)


# @@protoc_insertion_point(module_scope)
