# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/badge/awarded_gym_badge.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.enums import gym_badge_type_pb2 as pogoprotos_dot_enums_dot_gym__badge__type__pb2
from pogoprotos.data.badge import gym_badge_stats_pb2 as pogoprotos_dot_data_dot_badge_dot_gym__badge__stats__pb2
from pogoprotos.data.raid import player_raid_info_pb2 as pogoprotos_dot_data_dot_raid_dot_player__raid__info__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/badge/awarded_gym_badge.proto',
  package='pogoprotos.data.badge',
  syntax='proto3',
  serialized_pb=_b('\n-pogoprotos/data/badge/awarded_gym_badge.proto\x12\x15pogoprotos.data.badge\x1a%pogoprotos/enums/gym_badge_type.proto\x1a+pogoprotos/data/badge/gym_badge_stats.proto\x1a+pogoprotos/data/raid/player_raid_info.proto\"\xb6\x03\n\x0f\x41wardedGymBadge\x12\x0f\n\x07\x66ort_id\x18\x01 \x01(\t\x12\x36\n\x0egym_badge_type\x18\x02 \x01(\x0e\x32\x1e.pogoprotos.enums.GymBadgeType\x12\r\n\x05score\x18\x03 \x01(\r\x12=\n\x0fgym_badge_stats\x18\x04 \x01(\x0b\x32$.pogoprotos.data.badge.GymBadgeStats\x12 \n\x18last_update_timestamp_ms\x18\x05 \x01(\x04\x12\x1f\n\x17last_check_timestamp_ms\x18\x0b \x01(\x04\x12\x15\n\rearned_points\x18\x0c \x01(\r\x12\x10\n\x08progress\x18\r \x01(\x02\x12\x10\n\x08level_up\x18\x0e \x01(\x08\x12\x0c\n\x04name\x18\x06 \x01(\t\x12\x11\n\timage_url\x18\x07 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x08 \x01(\t\x12\x10\n\x08latitude\x18\t \x01(\x01\x12\x11\n\tlongitude\x18\n \x01(\x01\x12\x33\n\x05raids\x18\x0f \x01(\x0b\x32$.pogoprotos.data.raid.PlayerRaidInfob\x06proto3')
  ,
  dependencies=[pogoprotos_dot_enums_dot_gym__badge__type__pb2.DESCRIPTOR,pogoprotos_dot_data_dot_badge_dot_gym__badge__stats__pb2.DESCRIPTOR,pogoprotos_dot_data_dot_raid_dot_player__raid__info__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_AWARDEDGYMBADGE = _descriptor.Descriptor(
  name='AwardedGymBadge',
  full_name='pogoprotos.data.badge.AwardedGymBadge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fort_id', full_name='pogoprotos.data.badge.AwardedGymBadge.fort_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gym_badge_type', full_name='pogoprotos.data.badge.AwardedGymBadge.gym_badge_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='pogoprotos.data.badge.AwardedGymBadge.score', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gym_badge_stats', full_name='pogoprotos.data.badge.AwardedGymBadge.gym_badge_stats', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_update_timestamp_ms', full_name='pogoprotos.data.badge.AwardedGymBadge.last_update_timestamp_ms', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_check_timestamp_ms', full_name='pogoprotos.data.badge.AwardedGymBadge.last_check_timestamp_ms', index=5,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='earned_points', full_name='pogoprotos.data.badge.AwardedGymBadge.earned_points', index=6,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='progress', full_name='pogoprotos.data.badge.AwardedGymBadge.progress', index=7,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level_up', full_name='pogoprotos.data.badge.AwardedGymBadge.level_up', index=8,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='pogoprotos.data.badge.AwardedGymBadge.name', index=9,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_url', full_name='pogoprotos.data.badge.AwardedGymBadge.image_url', index=10,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='pogoprotos.data.badge.AwardedGymBadge.description', index=11,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='pogoprotos.data.badge.AwardedGymBadge.latitude', index=12,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='pogoprotos.data.badge.AwardedGymBadge.longitude', index=13,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='raids', full_name='pogoprotos.data.badge.AwardedGymBadge.raids', index=14,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=640,
)

_AWARDEDGYMBADGE.fields_by_name['gym_badge_type'].enum_type = pogoprotos_dot_enums_dot_gym__badge__type__pb2._GYMBADGETYPE
_AWARDEDGYMBADGE.fields_by_name['gym_badge_stats'].message_type = pogoprotos_dot_data_dot_badge_dot_gym__badge__stats__pb2._GYMBADGESTATS
_AWARDEDGYMBADGE.fields_by_name['raids'].message_type = pogoprotos_dot_data_dot_raid_dot_player__raid__info__pb2._PLAYERRAIDINFO
DESCRIPTOR.message_types_by_name['AwardedGymBadge'] = _AWARDEDGYMBADGE

AwardedGymBadge = _reflection.GeneratedProtocolMessageType('AwardedGymBadge', (_message.Message,), dict(
  DESCRIPTOR = _AWARDEDGYMBADGE,
  __module__ = 'pogoprotos.data.badge.awarded_gym_badge_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.badge.AwardedGymBadge)
  ))
_sym_db.RegisterMessage(AwardedGymBadge)


# @@protoc_insertion_point(module_scope)
