# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/platform/requests/buy_item_android_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/platform/requests/buy_item_android_request.proto',
  package='pogoprotos.networking.platform.requests',
  syntax='proto3',
  serialized_pb=_b('\nFpogoprotos/networking/platform/requests/buy_item_android_request.proto\x12\'pogoprotos.networking.platform.requests\"0\n\x15\x42uyItemAndroidRequest\x12\x17\n\x0f\x62uy_item_intent\x18\x01 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BUYITEMANDROIDREQUEST = _descriptor.Descriptor(
  name='BuyItemAndroidRequest',
  full_name='pogoprotos.networking.platform.requests.BuyItemAndroidRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='buy_item_intent', full_name='pogoprotos.networking.platform.requests.BuyItemAndroidRequest.buy_item_intent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=163,
)

DESCRIPTOR.message_types_by_name['BuyItemAndroidRequest'] = _BUYITEMANDROIDREQUEST

BuyItemAndroidRequest = _reflection.GeneratedProtocolMessageType('BuyItemAndroidRequest', (_message.Message,), dict(
  DESCRIPTOR = _BUYITEMANDROIDREQUEST,
  __module__ = 'pogoprotos.networking.platform.requests.buy_item_android_request_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.platform.requests.BuyItemAndroidRequest)
  ))
_sym_db.RegisterMessage(BuyItemAndroidRequest)


# @@protoc_insertion_point(module_scope)
