# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/use_item_encounter_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.data.capture import capture_probability_pb2 as pogoprotos_dot_data_dot_capture_dot_capture__probability__pb2
from pogoprotos.inventory.item import item_id_pb2 as pogoprotos_dot_inventory_dot_item_dot_item__id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/responses/use_item_encounter_response.proto',
  package='pogoprotos.networking.responses',
  syntax='proto3',
  serialized_pb=_b('\nApogoprotos/networking/responses/use_item_encounter_response.proto\x12\x1fpogoprotos.networking.responses\x1a\x31pogoprotos/data/capture/capture_probability.proto\x1a\'pogoprotos/inventory/item/item_id.proto\"\xe9\x02\n\x18UseItemEncounterResponse\x12P\n\x06status\x18\x01 \x01(\x0e\x32@.pogoprotos.networking.responses.UseItemEncounterResponse.Status\x12H\n\x13\x63\x61pture_probability\x18\x02 \x01(\x0b\x32+.pogoprotos.data.capture.CaptureProbability\x12\x36\n\x0b\x61\x63tive_item\x18\x03 \x01(\x0e\x32!.pogoprotos.inventory.item.ItemId\"y\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x15\n\x11\x41LREADY_COMPLETED\x10\x01\x12\x16\n\x12\x41\x43TIVE_ITEM_EXISTS\x10\x02\x12\x18\n\x14NO_ITEM_IN_INVENTORY\x10\x03\x12\x19\n\x15INVALID_ITEM_CATEGORY\x10\x04\x62\x06proto3')
  ,
  dependencies=[pogoprotos_dot_data_dot_capture_dot_capture__probability__pb2.DESCRIPTOR,pogoprotos_dot_inventory_dot_item_dot_item__id__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_USEITEMENCOUNTERRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='pogoprotos.networking.responses.UseItemEncounterResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALREADY_COMPLETED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVE_ITEM_EXISTS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_ITEM_IN_INVENTORY', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_ITEM_CATEGORY', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=435,
  serialized_end=556,
)
_sym_db.RegisterEnumDescriptor(_USEITEMENCOUNTERRESPONSE_STATUS)


_USEITEMENCOUNTERRESPONSE = _descriptor.Descriptor(
  name='UseItemEncounterResponse',
  full_name='pogoprotos.networking.responses.UseItemEncounterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='pogoprotos.networking.responses.UseItemEncounterResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='capture_probability', full_name='pogoprotos.networking.responses.UseItemEncounterResponse.capture_probability', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='active_item', full_name='pogoprotos.networking.responses.UseItemEncounterResponse.active_item', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _USEITEMENCOUNTERRESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=556,
)

_USEITEMENCOUNTERRESPONSE.fields_by_name['status'].enum_type = _USEITEMENCOUNTERRESPONSE_STATUS
_USEITEMENCOUNTERRESPONSE.fields_by_name['capture_probability'].message_type = pogoprotos_dot_data_dot_capture_dot_capture__probability__pb2._CAPTUREPROBABILITY
_USEITEMENCOUNTERRESPONSE.fields_by_name['active_item'].enum_type = pogoprotos_dot_inventory_dot_item_dot_item__id__pb2._ITEMID
_USEITEMENCOUNTERRESPONSE_STATUS.containing_type = _USEITEMENCOUNTERRESPONSE
DESCRIPTOR.message_types_by_name['UseItemEncounterResponse'] = _USEITEMENCOUNTERRESPONSE

UseItemEncounterResponse = _reflection.GeneratedProtocolMessageType('UseItemEncounterResponse', (_message.Message,), dict(
  DESCRIPTOR = _USEITEMENCOUNTERRESPONSE,
  __module__ = 'pogoprotos.networking.responses.use_item_encounter_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.UseItemEncounterResponse)
  ))
_sym_db.RegisterMessage(UseItemEncounterResponse)


# @@protoc_insertion_point(module_scope)
