# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/background_token.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/background_token.proto',
  package='pogoprotos.data',
  syntax='proto3',
  serialized_pb=_b('\n&pogoprotos/data/background_token.proto\x12\x0fpogoprotos.data\"E\n\x0f\x42\x61\x63kgroundToken\x12\r\n\x05token\x18\x01 \x01(\x0c\x12\x17\n\x0f\x65xpiration_time\x18\x02 \x01(\x03\x12\n\n\x02iv\x18\x03 \x01(\x0c\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BACKGROUNDTOKEN = _descriptor.Descriptor(
  name='BackgroundToken',
  full_name='pogoprotos.data.BackgroundToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='pogoprotos.data.BackgroundToken.token', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expiration_time', full_name='pogoprotos.data.BackgroundToken.expiration_time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iv', full_name='pogoprotos.data.BackgroundToken.iv', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=128,
)

DESCRIPTOR.message_types_by_name['BackgroundToken'] = _BACKGROUNDTOKEN

BackgroundToken = _reflection.GeneratedProtocolMessageType('BackgroundToken', (_message.Message,), dict(
  DESCRIPTOR = _BACKGROUNDTOKEN,
  __module__ = 'pogoprotos.data.background_token_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.BackgroundToken)
  ))
_sym_db.RegisterMessage(BackgroundToken)


# @@protoc_insertion_point(module_scope)
