# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/quests/multi_part_quest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.data.quests import quest_pb2 as pogoprotos_dot_data_dot_quests_dot_quest__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/quests/multi_part_quest.proto',
  package='pogoprotos.data.quests',
  syntax='proto3',
  serialized_pb=_b('\n-pogoprotos/data/quests/multi_part_quest.proto\x12\x16pogoprotos.data.quests\x1a\"pogoprotos/data/quests/quest.proto\"C\n\x0eMultiPartQuest\x12\x31\n\nsub_quests\x18\x01 \x03(\x0b\x32\x1d.pogoprotos.data.quests.Questb\x06proto3')
  ,
  dependencies=[pogoprotos_dot_data_dot_quests_dot_quest__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MULTIPARTQUEST = _descriptor.Descriptor(
  name='MultiPartQuest',
  full_name='pogoprotos.data.quests.MultiPartQuest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sub_quests', full_name='pogoprotos.data.quests.MultiPartQuest.sub_quests', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=176,
)

_MULTIPARTQUEST.fields_by_name['sub_quests'].message_type = pogoprotos_dot_data_dot_quests_dot_quest__pb2._QUEST
DESCRIPTOR.message_types_by_name['MultiPartQuest'] = _MULTIPARTQUEST

MultiPartQuest = _reflection.GeneratedProtocolMessageType('MultiPartQuest', (_message.Message,), dict(
  DESCRIPTOR = _MULTIPARTQUEST,
  __module__ = 'pogoprotos.data.quests.multi_part_quest_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.quests.MultiPartQuest)
  ))
_sym_db.RegisterMessage(MultiPartQuest)


# @@protoc_insertion_point(module_scope)
