# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/quests/quest_reward.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/quests/quest_reward.proto',
  package='pogoprotos.data.quests',
  syntax='proto3',
  serialized_pb=_b('\n)pogoprotos/data/quests/quest_reward.proto\x12\x16pogoprotos.data.quests\"\x8a\x02\n\x0bQuestReward\x12\x36\n\x04type\x18\x01 \x01(\x0e\x32(.pogoprotos.data.quests.QuestReward.Type\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\x12\x15\n\rpokemon_index\x18\x03 \x01(\x05\x12\x0f\n\x07item_id\x18\x04 \x01(\x05\x12\x19\n\x11quest_template_id\x18\x05 \x01(\t\"p\n\x04Type\x12\x0e\n\nEXPERIENCE\x10\x00\x12\x08\n\x04ITEM\x10\x01\x12\x15\n\x11POKEMON_ENCOUNTER\x10\x02\x12\x0c\n\x08STARDUST\x10\x03\x12\t\n\x05\x43\x41NDY\x10\x04\x12\x13\n\x0f\x41VATAR_CLOTHING\x10\x05\x12\t\n\x05QUEST\x10\x06\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_QUESTREWARD_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='pogoprotos.data.quests.QuestReward.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EXPERIENCE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POKEMON_ENCOUNTER', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STARDUST', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CANDY', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AVATAR_CLOTHING', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUEST', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=224,
  serialized_end=336,
)
_sym_db.RegisterEnumDescriptor(_QUESTREWARD_TYPE)


_QUESTREWARD = _descriptor.Descriptor(
  name='QuestReward',
  full_name='pogoprotos.data.quests.QuestReward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='pogoprotos.data.quests.QuestReward.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='pogoprotos.data.quests.QuestReward.amount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pokemon_index', full_name='pogoprotos.data.quests.QuestReward.pokemon_index', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item_id', full_name='pogoprotos.data.quests.QuestReward.item_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quest_template_id', full_name='pogoprotos.data.quests.QuestReward.quest_template_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _QUESTREWARD_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=336,
)

_QUESTREWARD.fields_by_name['type'].enum_type = _QUESTREWARD_TYPE
_QUESTREWARD_TYPE.containing_type = _QUESTREWARD
DESCRIPTOR.message_types_by_name['QuestReward'] = _QUESTREWARD

QuestReward = _reflection.GeneratedProtocolMessageType('QuestReward', (_message.Message,), dict(
  DESCRIPTOR = _QUESTREWARD,
  __module__ = 'pogoprotos.data.quests.quest_reward_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.quests.QuestReward)
  ))
_sym_db.RegisterMessage(QuestReward)


# @@protoc_insertion_point(module_scope)
