# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/enums/form.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/enums/form.proto',
  package='pogoprotos.enums',
  syntax='proto3',
  serialized_pb=_b('\n\x1bpogoprotos/enums/form.proto\x12\x10pogoprotos.enums*\x9e\x03\n\x04\x46orm\x12\x0e\n\nFORM_UNSET\x10\x00\x12\x0b\n\x07UNOWN_A\x10\x01\x12\x0b\n\x07UNOWN_B\x10\x02\x12\x0b\n\x07UNOWN_C\x10\x03\x12\x0b\n\x07UNOWN_D\x10\x04\x12\x0b\n\x07UNOWN_E\x10\x05\x12\x0b\n\x07UNOWN_F\x10\x06\x12\x0b\n\x07UNOWN_G\x10\x07\x12\x0b\n\x07UNOWN_H\x10\x08\x12\x0b\n\x07UNOWN_I\x10\t\x12\x0b\n\x07UNOWN_J\x10\n\x12\x0b\n\x07UNOWN_K\x10\x0b\x12\x0b\n\x07UNOWN_L\x10\x0c\x12\x0b\n\x07UNOWN_M\x10\r\x12\x0b\n\x07UNOWN_N\x10\x0e\x12\x0b\n\x07UNOWN_O\x10\x0f\x12\x0b\n\x07UNOWN_P\x10\x10\x12\x0b\n\x07UNOWN_Q\x10\x11\x12\x0b\n\x07UNOWN_R\x10\x12\x12\x0b\n\x07UNOWN_S\x10\x13\x12\x0b\n\x07UNOWN_T\x10\x14\x12\x0b\n\x07UNOWN_U\x10\x15\x12\x0b\n\x07UNOWN_V\x10\x16\x12\x0b\n\x07UNOWN_W\x10\x17\x12\x0b\n\x07UNOWN_X\x10\x18\x12\x0b\n\x07UNOWN_Y\x10\x19\x12\x0b\n\x07UNOWN_Z\x10\x1a\x12\x17\n\x13UNOWN_QUESTION_MARK\x10\x1b\x12\x1b\n\x17UNOWN_EXCLAMATION_POINT\x10\x1c\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_FORM = _descriptor.EnumDescriptor(
  name='Form',
  full_name='pogoprotos.enums.Form',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FORM_UNSET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_A', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_B', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_C', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_D', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_E', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_F', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_G', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_H', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_I', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_J', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_K', index=11, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_L', index=12, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_M', index=13, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_N', index=14, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_O', index=15, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_P', index=16, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_Q', index=17, number=17,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_R', index=18, number=18,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_S', index=19, number=19,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_T', index=20, number=20,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_U', index=21, number=21,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_V', index=22, number=22,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_W', index=23, number=23,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_X', index=24, number=24,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_Y', index=25, number=25,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_Z', index=26, number=26,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_QUESTION_MARK', index=27, number=27,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNOWN_EXCLAMATION_POINT', index=28, number=28,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=50,
  serialized_end=464,
)
_sym_db.RegisterEnumDescriptor(_FORM)

Form = enum_type_wrapper.EnumTypeWrapper(_FORM)
FORM_UNSET = 0
UNOWN_A = 1
UNOWN_B = 2
UNOWN_C = 3
UNOWN_D = 4
UNOWN_E = 5
UNOWN_F = 6
UNOWN_G = 7
UNOWN_H = 8
UNOWN_I = 9
UNOWN_J = 10
UNOWN_K = 11
UNOWN_L = 12
UNOWN_M = 13
UNOWN_N = 14
UNOWN_O = 15
UNOWN_P = 16
UNOWN_Q = 17
UNOWN_R = 18
UNOWN_S = 19
UNOWN_T = 20
UNOWN_U = 21
UNOWN_V = 22
UNOWN_W = 23
UNOWN_X = 24
UNOWN_Y = 25
UNOWN_Z = 26
UNOWN_QUESTION_MARK = 27
UNOWN_EXCLAMATION_POINT = 28


DESCRIPTOR.enum_types_by_name['Form'] = _FORM


# @@protoc_insertion_point(module_scope)
