# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/redeem/redeemed_item.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.inventory.item import item_id_pb2 as pogoprotos_dot_inventory_dot_item_dot_item__id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/redeem/redeemed_item.proto',
  package='pogoprotos.data.redeem',
  syntax='proto3',
  serialized_pb=_b('\n*pogoprotos/data/redeem/redeemed_item.proto\x12\x16pogoprotos.data.redeem\x1a\'pogoprotos/inventory/item/item_id.proto\"S\n\x0cRedeemedItem\x12/\n\x04item\x18\x01 \x01(\x0e\x32!.pogoprotos.inventory.item.ItemId\x12\x12\n\nitem_count\x18\x02 \x01(\x05\x62\x06proto3')
  ,
  dependencies=[pogoprotos_dot_inventory_dot_item_dot_item__id__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REDEEMEDITEM = _descriptor.Descriptor(
  name='RedeemedItem',
  full_name='pogoprotos.data.redeem.RedeemedItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='pogoprotos.data.redeem.RedeemedItem.item', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item_count', full_name='pogoprotos.data.redeem.RedeemedItem.item_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=194,
)

_REDEEMEDITEM.fields_by_name['item'].enum_type = pogoprotos_dot_inventory_dot_item_dot_item__id__pb2._ITEMID
DESCRIPTOR.message_types_by_name['RedeemedItem'] = _REDEEMEDITEM

RedeemedItem = _reflection.GeneratedProtocolMessageType('RedeemedItem', (_message.Message,), dict(
  DESCRIPTOR = _REDEEMEDITEM,
  __module__ = 'pogoprotos.data.redeem.redeemed_item_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.redeem.RedeemedItem)
  ))
_sym_db.RegisterMessage(RedeemedItem)


# @@protoc_insertion_point(module_scope)
