# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/collect_daily_defender_bonus_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/messages/collect_daily_defender_bonus_message.proto',
  package='pogoprotos.networking.requests.messages',
  syntax='proto3',
  serialized_pb=_b('\nRpogoprotos/networking/requests/messages/collect_daily_defender_bonus_message.proto\x12\'pogoprotos.networking.requests.messages\"\"\n CollectDailyDefenderBonusMessageb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COLLECTDAILYDEFENDERBONUSMESSAGE = _descriptor.Descriptor(
  name='CollectDailyDefenderBonusMessage',
  full_name='pogoprotos.networking.requests.messages.CollectDailyDefenderBonusMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=161,
)

DESCRIPTOR.message_types_by_name['CollectDailyDefenderBonusMessage'] = _COLLECTDAILYDEFENDERBONUSMESSAGE

CollectDailyDefenderBonusMessage = _reflection.GeneratedProtocolMessageType('CollectDailyDefenderBonusMessage', (_message.Message,), dict(
  DESCRIPTOR = _COLLECTDAILYDEFENDERBONUSMESSAGE,
  __module__ = 'pogoprotos.networking.requests.messages.collect_daily_defender_bonus_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.messages.CollectDailyDefenderBonusMessage)
  ))
_sym_db.RegisterMessage(CollectDailyDefenderBonusMessage)


# @@protoc_insertion_point(module_scope)
