# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/get_player_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/messages/get_player_message.proto',
  package='pogoprotos.networking.requests.messages',
  syntax='proto3',
  serialized_pb=_b('\n@pogoprotos/networking/requests/messages/get_player_message.proto\x12\'pogoprotos.networking.requests.messages\"\xd0\x01\n\x10GetPlayerMessage\x12]\n\rplayer_locale\x18\x01 \x01(\x0b\x32\x46.pogoprotos.networking.requests.messages.GetPlayerMessage.PlayerLocale\x12\x18\n\x10prevent_creation\x18\x02 \x01(\x08\x1a\x43\n\x0cPlayerLocale\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x10\n\x08timezone\x18\x03 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETPLAYERMESSAGE_PLAYERLOCALE = _descriptor.Descriptor(
  name='PlayerLocale',
  full_name='pogoprotos.networking.requests.messages.GetPlayerMessage.PlayerLocale',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='country', full_name='pogoprotos.networking.requests.messages.GetPlayerMessage.PlayerLocale.country', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='language', full_name='pogoprotos.networking.requests.messages.GetPlayerMessage.PlayerLocale.language', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timezone', full_name='pogoprotos.networking.requests.messages.GetPlayerMessage.PlayerLocale.timezone', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=318,
)

_GETPLAYERMESSAGE = _descriptor.Descriptor(
  name='GetPlayerMessage',
  full_name='pogoprotos.networking.requests.messages.GetPlayerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_locale', full_name='pogoprotos.networking.requests.messages.GetPlayerMessage.player_locale', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prevent_creation', full_name='pogoprotos.networking.requests.messages.GetPlayerMessage.prevent_creation', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GETPLAYERMESSAGE_PLAYERLOCALE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=318,
)

_GETPLAYERMESSAGE_PLAYERLOCALE.containing_type = _GETPLAYERMESSAGE
_GETPLAYERMESSAGE.fields_by_name['player_locale'].message_type = _GETPLAYERMESSAGE_PLAYERLOCALE
DESCRIPTOR.message_types_by_name['GetPlayerMessage'] = _GETPLAYERMESSAGE

GetPlayerMessage = _reflection.GeneratedProtocolMessageType('GetPlayerMessage', (_message.Message,), dict(

  PlayerLocale = _reflection.GeneratedProtocolMessageType('PlayerLocale', (_message.Message,), dict(
    DESCRIPTOR = _GETPLAYERMESSAGE_PLAYERLOCALE,
    __module__ = 'pogoprotos.networking.requests.messages.get_player_message_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.messages.GetPlayerMessage.PlayerLocale)
    ))
  ,
  DESCRIPTOR = _GETPLAYERMESSAGE,
  __module__ = 'pogoprotos.networking.requests.messages.get_player_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.messages.GetPlayerMessage)
  ))
_sym_db.RegisterMessage(GetPlayerMessage)
_sym_db.RegisterMessage(GetPlayerMessage.PlayerLocale)


# @@protoc_insertion_point(module_scope)
