# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/get_inbox_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/messages/get_inbox_message.proto',
  package='pogoprotos.networking.requests.messages',
  syntax='proto3',
  serialized_pb=_b('\n?pogoprotos/networking/requests/messages/get_inbox_message.proto\x12\'pogoprotos.networking.requests.messages\"P\n\x0fGetInboxMessage\x12\x12\n\nis_history\x18\x01 \x01(\x08\x12\x12\n\nis_reverse\x18\x02 \x01(\x08\x12\x15\n\rnot_before_ms\x18\x03 \x01(\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETINBOXMESSAGE = _descriptor.Descriptor(
  name='GetInboxMessage',
  full_name='pogoprotos.networking.requests.messages.GetInboxMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_history', full_name='pogoprotos.networking.requests.messages.GetInboxMessage.is_history', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_reverse', full_name='pogoprotos.networking.requests.messages.GetInboxMessage.is_reverse', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='not_before_ms', full_name='pogoprotos.networking.requests.messages.GetInboxMessage.not_before_ms', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=188,
)

DESCRIPTOR.message_types_by_name['GetInboxMessage'] = _GETINBOXMESSAGE

GetInboxMessage = _reflection.GeneratedProtocolMessageType('GetInboxMessage', (_message.Message,), dict(
  DESCRIPTOR = _GETINBOXMESSAGE,
  __module__ = 'pogoprotos.networking.requests.messages.get_inbox_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.messages.GetInboxMessage)
  ))
_sym_db.RegisterMessage(GetInboxMessage)


# @@protoc_insertion_point(module_scope)
