# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/platform_client_actions_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/messages/platform_client_actions_message.proto',
  package='pogoprotos.networking.requests.messages',
  syntax='proto3',
  serialized_pb=_b('\nMpogoprotos/networking/requests/messages/platform_client_actions_message.proto\x12\'pogoprotos.networking.requests.messages\"\xed\x02\n\x1fRegisterPushNotificationMessage\x12\x64\n\tapn_token\x18\x01 \x01(\x0b\x32Q.pogoprotos.networking.requests.messages.RegisterPushNotificationMessage.ApnToken\x12\x64\n\tgcm_token\x18\x02 \x01(\x0b\x32Q.pogoprotos.networking.requests.messages.RegisterPushNotificationMessage.GcmToken\x1aY\n\x08\x41pnToken\x12\x17\n\x0fregistration_id\x18\x01 \x01(\t\x12\x19\n\x11\x62undle_identifier\x18\x02 \x01(\t\x12\x19\n\x11payload_byte_size\x18\x03 \x01(\x05\x1a#\n\x08GcmToken\x12\x17\n\x0fregistration_id\x18\x01 \x01(\t\"\xf5\x01\n\x1fUpdateNotificationStatusMessage\x12\x18\n\x10notification_ids\x18\x01 \x03(\t\x12\x1b\n\x13\x63reate_timestamp_ms\x18\x02 \x03(\x03\x12i\n\x05state\x18\x03 \x01(\x0e\x32Z.pogoprotos.networking.requests.messages.UpdateNotificationStatusMessage.NotificationState\"0\n\x11NotificationState\x12\x0f\n\x0bUNSET_STATE\x10\x00\x12\n\n\x06VIEWED\x10\x01\";\n%OptOutPushNotificationCategoryMessage\x12\x12\n\ncategories\x18\x01 \x03(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_UPDATENOTIFICATIONSTATUSMESSAGE_NOTIFICATIONSTATE = _descriptor.EnumDescriptor(
  name='NotificationState',
  full_name='pogoprotos.networking.requests.messages.UpdateNotificationStatusMessage.NotificationState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET_STATE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VIEWED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=688,
  serialized_end=736,
)
_sym_db.RegisterEnumDescriptor(_UPDATENOTIFICATIONSTATUSMESSAGE_NOTIFICATIONSTATE)


_REGISTERPUSHNOTIFICATIONMESSAGE_APNTOKEN = _descriptor.Descriptor(
  name='ApnToken',
  full_name='pogoprotos.networking.requests.messages.RegisterPushNotificationMessage.ApnToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='registration_id', full_name='pogoprotos.networking.requests.messages.RegisterPushNotificationMessage.ApnToken.registration_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bundle_identifier', full_name='pogoprotos.networking.requests.messages.RegisterPushNotificationMessage.ApnToken.bundle_identifier', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload_byte_size', full_name='pogoprotos.networking.requests.messages.RegisterPushNotificationMessage.ApnToken.payload_byte_size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=451,
)

_REGISTERPUSHNOTIFICATIONMESSAGE_GCMTOKEN = _descriptor.Descriptor(
  name='GcmToken',
  full_name='pogoprotos.networking.requests.messages.RegisterPushNotificationMessage.GcmToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='registration_id', full_name='pogoprotos.networking.requests.messages.RegisterPushNotificationMessage.GcmToken.registration_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=453,
  serialized_end=488,
)

_REGISTERPUSHNOTIFICATIONMESSAGE = _descriptor.Descriptor(
  name='RegisterPushNotificationMessage',
  full_name='pogoprotos.networking.requests.messages.RegisterPushNotificationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='apn_token', full_name='pogoprotos.networking.requests.messages.RegisterPushNotificationMessage.apn_token', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gcm_token', full_name='pogoprotos.networking.requests.messages.RegisterPushNotificationMessage.gcm_token', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REGISTERPUSHNOTIFICATIONMESSAGE_APNTOKEN, _REGISTERPUSHNOTIFICATIONMESSAGE_GCMTOKEN, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=488,
)


_UPDATENOTIFICATIONSTATUSMESSAGE = _descriptor.Descriptor(
  name='UpdateNotificationStatusMessage',
  full_name='pogoprotos.networking.requests.messages.UpdateNotificationStatusMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='notification_ids', full_name='pogoprotos.networking.requests.messages.UpdateNotificationStatusMessage.notification_ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='create_timestamp_ms', full_name='pogoprotos.networking.requests.messages.UpdateNotificationStatusMessage.create_timestamp_ms', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='pogoprotos.networking.requests.messages.UpdateNotificationStatusMessage.state', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _UPDATENOTIFICATIONSTATUSMESSAGE_NOTIFICATIONSTATE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=736,
)


_OPTOUTPUSHNOTIFICATIONCATEGORYMESSAGE = _descriptor.Descriptor(
  name='OptOutPushNotificationCategoryMessage',
  full_name='pogoprotos.networking.requests.messages.OptOutPushNotificationCategoryMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='categories', full_name='pogoprotos.networking.requests.messages.OptOutPushNotificationCategoryMessage.categories', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=738,
  serialized_end=797,
)

_REGISTERPUSHNOTIFICATIONMESSAGE_APNTOKEN.containing_type = _REGISTERPUSHNOTIFICATIONMESSAGE
_REGISTERPUSHNOTIFICATIONMESSAGE_GCMTOKEN.containing_type = _REGISTERPUSHNOTIFICATIONMESSAGE
_REGISTERPUSHNOTIFICATIONMESSAGE.fields_by_name['apn_token'].message_type = _REGISTERPUSHNOTIFICATIONMESSAGE_APNTOKEN
_REGISTERPUSHNOTIFICATIONMESSAGE.fields_by_name['gcm_token'].message_type = _REGISTERPUSHNOTIFICATIONMESSAGE_GCMTOKEN
_UPDATENOTIFICATIONSTATUSMESSAGE.fields_by_name['state'].enum_type = _UPDATENOTIFICATIONSTATUSMESSAGE_NOTIFICATIONSTATE
_UPDATENOTIFICATIONSTATUSMESSAGE_NOTIFICATIONSTATE.containing_type = _UPDATENOTIFICATIONSTATUSMESSAGE
DESCRIPTOR.message_types_by_name['RegisterPushNotificationMessage'] = _REGISTERPUSHNOTIFICATIONMESSAGE
DESCRIPTOR.message_types_by_name['UpdateNotificationStatusMessage'] = _UPDATENOTIFICATIONSTATUSMESSAGE
DESCRIPTOR.message_types_by_name['OptOutPushNotificationCategoryMessage'] = _OPTOUTPUSHNOTIFICATIONCATEGORYMESSAGE

RegisterPushNotificationMessage = _reflection.GeneratedProtocolMessageType('RegisterPushNotificationMessage', (_message.Message,), dict(

  ApnToken = _reflection.GeneratedProtocolMessageType('ApnToken', (_message.Message,), dict(
    DESCRIPTOR = _REGISTERPUSHNOTIFICATIONMESSAGE_APNTOKEN,
    __module__ = 'pogoprotos.networking.requests.messages.platform_client_actions_message_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.messages.RegisterPushNotificationMessage.ApnToken)
    ))
  ,

  GcmToken = _reflection.GeneratedProtocolMessageType('GcmToken', (_message.Message,), dict(
    DESCRIPTOR = _REGISTERPUSHNOTIFICATIONMESSAGE_GCMTOKEN,
    __module__ = 'pogoprotos.networking.requests.messages.platform_client_actions_message_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.messages.RegisterPushNotificationMessage.GcmToken)
    ))
  ,
  DESCRIPTOR = _REGISTERPUSHNOTIFICATIONMESSAGE,
  __module__ = 'pogoprotos.networking.requests.messages.platform_client_actions_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.messages.RegisterPushNotificationMessage)
  ))
_sym_db.RegisterMessage(RegisterPushNotificationMessage)
_sym_db.RegisterMessage(RegisterPushNotificationMessage.ApnToken)
_sym_db.RegisterMessage(RegisterPushNotificationMessage.GcmToken)

UpdateNotificationStatusMessage = _reflection.GeneratedProtocolMessageType('UpdateNotificationStatusMessage', (_message.Message,), dict(
  DESCRIPTOR = _UPDATENOTIFICATIONSTATUSMESSAGE,
  __module__ = 'pogoprotos.networking.requests.messages.platform_client_actions_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.messages.UpdateNotificationStatusMessage)
  ))
_sym_db.RegisterMessage(UpdateNotificationStatusMessage)

OptOutPushNotificationCategoryMessage = _reflection.GeneratedProtocolMessageType('OptOutPushNotificationCategoryMessage', (_message.Message,), dict(
  DESCRIPTOR = _OPTOUTPUSHNOTIFICATIONCATEGORYMESSAGE,
  __module__ = 'pogoprotos.networking.requests.messages.platform_client_actions_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.messages.OptOutPushNotificationCategoryMessage)
  ))
_sym_db.RegisterMessage(OptOutPushNotificationCategoryMessage)


# @@protoc_insertion_point(module_scope)
